<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TechEZone" failures="2" tests="9" name="firefoxtest_linux" time="82.513" errors="0" timestamp="2024-11-26T20:41:45 IST">
  <testcase classname="com.fitpeo.testcase.TC001_HomePageTest" name="verify_navigation_of_homepage" time="0.774"/>
  <testcase classname="com.fitpeo.testcase.TC002_RevenueCalculatorTest" name="verify_navigation_of_revenue_calculator" time="1.835"/>
  <testcase classname="com.fitpeo.testcase.TC002_RevenueCalculatorTest" name="verify_page_is_scrollable_till_the_slider" time="0.05"/>
  <testcase classname="com.fitpeo.testcase.TC002_RevenueCalculatorTest" name="verify_the_slider_is_adjustable_till_the_value" time="1.256"/>
  <testcase classname="com.fitpeo.testcase.TC002_RevenueCalculatorTest" name="validate_the_slider_value_and_input_value" time="0.148">
    <failure type="java.lang.AssertionError" message="expected [820] but found [1343]">
      <![CDATA[java.lang.AssertionError: expected [820] but found [1343]
at com.fitpeo.testcase.TC002_RevenueCalculatorTest.validate_the_slider_value_and_input_value(TC002_RevenueCalculatorTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- validate_the_slider_value_and_input_value -->
  <testcase classname="com.fitpeo.testcase.TC002_RevenueCalculatorTest" name="verify_the_slider_input_value_updatable" time="1.327"/>
  <testcase classname="com.fitpeo.testcase.TC002_RevenueCalculatorTest" name="validate_the_slidervalue_with_updated_sliderinput" time="0.096"/>
  <testcase classname="com.fitpeo.testcase.TC002_RevenueCalculatorTest" name="verify_the_cptCodes_are_clickable" time="3.794"/>
  <testcase classname="com.fitpeo.testcase.TC002_RevenueCalculatorTest" name="verify_the_total_recurring_reimbursement" time="31.174">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.fitpeo.testcase.TC002_RevenueCalculatorTest.verify_the_total_recurring_reimbursement(TC002_RevenueCalculatorTest.java:124)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verify_the_total_recurring_reimbursement -->
</testsuite> <!-- firefoxtest_linux -->
